### PR TITLE
Making PushMessageDataInit a union

### LINKED ISSUE #159: Binary messages and use of `USVString` in `PushMessageDataInit`
Section 10 states "`PushMessageData` objects have an associated bytes (a byte sequence) set on creation." Given that—and the `blob()` and `arrayBuffer()` methods—I'm curious why `PushMessageDataInit` uses `USVString` instead of, e.g., `ArrayBuffer`. Does this mean that all decrypted messages must be UTF-8 encoded strings?

### PR DESCRIPTION
**Pull request by martinthomson**
Fixes #159.

### CODE REVIEW

**Comment by annevk** [comment]
This seems bad. You shouldn't be able to read a `Blob` synchronously.

**Comment by martinthomson** [comment]
Hmm, you make a good point.  Should I give up on Blob?

**Comment by annevk** [comment]
Yeah, and instead of DOMString you want USVString so lone surrogates get replaced.

**Comment by martinthomson** [comment]
I've never understood the insistence on USVString; don't we to want to insist on inputs having no lone surrogates?

**Comment by annevk** [comment]
A normal JavaScript string doesn't insist on it and DOMString goes along with that. However, whenever you have a string that needs to go over the network or become a URL they do become a problem. So at that point you'd use USVString.

**Comment by martinthomson** [comment]
And I finally understand.  Updated.

I will send @heycam a PR for WebIDL, because the explanation there is woefully inadequate.

**Comment by beverloo** [comment]
This seems good to me.

**Pull request merged**
