### PR TITLE
Add tidyconfig.txt and tidy the spec.

### PR DESCRIPTION
**Pull request by mounirlamouri**
@efullea can you have a look?

### CODE REVIEW

**Comment by efullea** [comment]
This PR may collide with other open PRs. I suggest waiting till the open PRs are closed to avoid merging problems.

**Comment by mounirlamouri** [comment]
@efullea there will always be PR on their way. 2 out of 4 PRs are currently applying on top of tree. I think it's fine to break them. Otherwise, we will never be able to land this.

@mvanouwerkerk would you be okay to rebase your PR on top of this?

**Comment by mounirlamouri** [comment]
Oups, I tidyconfig.txt wasn't there. Added.

**Comment by mounirlamouri** [comment]
@efullea is it good to merge?

**Pull request merged**
