### PR TITLE
chore(.travis): set up validation

### PR DESCRIPTION
**Pull request by marcoscaceres**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/push-api/pull/307.html" title="Last updated on May 30, 2019, 3:34 AM UTC (21c8a57)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/push-api/307/eda4fe0...21c8a57.html" title="Last updated on May 30, 2019, 3:34 AM UTC (21c8a57)">Diff</a>

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@beverloo, I've refactored the spec to use new ReSpec stuff, fixed the ReSpec warnings, and fixup some terminology. This will allow us to move the spec back onto auto-publishing, and we get assurances that the links don't each time we republish.

**Comment by marcoscaceres** [comment]
Need to check what's going on with that NIST PDF that's not linking... same with the secure context link :/

**Comment by martinthomson** [comment]
Renaming the tidy config breaks the makefile.  Also, `https://ev.buaa.edu.cn/` seems like an odd thing to need to be requested.

**Comment by marcoscaceres** [comment]
Will revert the file name. 

> Also, https://ev.buaa.edu.cn/

That’s from the w3c copyright. Unfortunately, that NIST PDF means I need to use GET.

**Comment by marcoscaceres** [comment]
Sorry for all the noise on this. Travis is finally happy and cross references are now all good 🥳

**Comment by marcoscaceres** [comment]
Moving forward with this as issues were addressed... it's blocking me from finishing some set up of the new working group.

Happy to continue helping with editorial tasks going forward. Just let me know :)

**Pull request merged**
