### PR TITLE
Rename pushEndpoint to endpoint. Fixes issue #31

### PR DESCRIPTION
**Pull request by mvano**

### CODE REVIEW

**Comment by beverloo** [comment]
It seems inconsistent to rename pushEndpoint to endpoint, but not rename pushRegistrationId to registrationId.

**Comment by beverloo** [comment]
Ah, that's issue #30. Why not do both in the same patch?

It would be great if we could get some more input on these issues.

**Comment by mvano** [comment]
I'm splitting these into small changes where possible, to avoid merge conflicts and make reviewing easier.

Agreed that more input from more people and companies would be welcome. While we're working on Github I think visibility is a bit limited. However, the current state of the spec is inconsistent, and asking people to read it is likely to be wasteful. Once the spec is more or less up to date with the discussions and implementations I'd like to request more input from public-webapps.

**Comment by beverloo** [comment]
LGTM, when both will be applied. The interface name (PushRegistration) itself is clear enough.

**Comment by mvano** [comment]
Also renamed `pushRegistrationId` to `registrationId`.

**Comment by mvano** [comment]
@efullea I think this is ready to be merged.

**Comment by mvano** [comment]
Rebased. Should be good now @efullea

**Pull request merged**
