### PR TITLE
Editorial: use new constructor IDL syntax

### LINKED ISSUE #318: Update to constructor operations
See https://github.com/heycam/webidl/issues/778.

### PR DESCRIPTION
**Pull request by marcoscaceres**
Closes #318

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/push-api/pull/319.html" title="Last updated on Aug 30, 2019, 5:41 AM UTC (f336ca7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/push-api/319/194bee8...f336ca7.html" title="Last updated on Aug 30, 2019, 5:41 AM UTC (f336ca7)">Diff</a>

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Blocked on ReSpec support. https://github.com/w3c/respec/issues/2494

**Comment by marcoscaceres** [comment]
Should be good to merge now - the Travis error is #315... @beverloo, maybe you can look at #315 while you are at it?

**Review by martinthomson — APPROVED** [review]
Why do we have to keep changing things...

**Comment by marcoscaceres** [comment]
> Why do we have to keep changing things...

Keeps us busy and employed, Martin 🤪

**Pull request merged**
