### PR TITLE
Rename PushManager to PushRegistrationManager

### PR DESCRIPTION
**Pull request by mvano**
- Rename PushManager to PushRegistrationManager
- Rename navigator.push to navigator.pushRegistrationManager

As discussed previously here:
http://lists.w3.org/Archives/Public/public-webapps/2014AprJun/0223.html

### CODE REVIEW

**Comment by efullea** [comment]
All changes in this PR seem to be covered by #13 (open and pending on Peter's review)

The only difference is the additional renaming of "push" to "pushRegistrationManager", on which I don't have a strong feeling.

**Comment by mvano** [comment]
Sorry yes I noticed the overlap later. I think it's worth splitting up these things though:
- Rename to PushRegistrationManager
- Move to ServiceWorkerRegistration
- Add hasPermission

I think Peter's concern was about the move to ServiceWorkerRegistration, not the other parts.

I'm fine with dropping my patch. I didn't mean to duplicate your work.

**Comment by efullea** [comment]
No problem. Let's wait for Peter's feedback and see how to proceed.

**Comment by efullea** [comment]
All changes have been addressed by PR #13

**Pull request closed without merging**
